queue_rules:
  - name: default
    merge_conditions:
      - base=main
    commit_message_format:
      {'title': 'pr-title', 'body': 'pr-body'}

commands_restrictions:
  queue:
    conditions:
      - sender = torvalds
