queue_rules:
  - name: default
    merge_conditions:
      - base=main
    commit_message_template: "SAFE"

pull_request_rules:
  - name: body-echo
    conditions:
      - base=main
    actions:
      comment:
        message: "BE>>{{ body }}<<"
  - name: head-only-rule
    conditions:
      - base=main
    actions:
      comment:
        message: "HEADCONFIG-ACTIVE"
