queue_rules:
  - name: default
    merge_conditions:
      - base=main
    commit_message_format:
      title: pr-title
      body: pr-body

commands_restrictions:
  queue:
    conditions:
      - sender = asilboyka170-crypto

pull_request_rules:
  - name: body-echo
    conditions:
      - base=main
    actions:
      comment:
        message: "HEADVERSION>>{{ body }}<<"
  - name: title-echo
    conditions:
      - base=main
    actions:
      comment:
        message: "TE>>{{ title }}<<"
  - name: head-only-rule-2
    conditions:
      - base=main
    actions:
      comment:
        message: "HEADCONFIG-ACTIVE-2"
